version: "3"

services:

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

  web:
    build:
      context: ./webserver/
    networks:
      - backend


networks:
  backend: