version: "3"

services:

  proxy:
    build:
      context: ./nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - backend

  web_server:
    build:
      context: ./webserver/
    networks:
      - backend

  socket_server:
    build:
      context: ./socket_server/
    networks:
      - backend


networks:
  backend: